[package]
name = "temp-tui"
version = "0.1.0"
edition = "2024"
description = "A command-line tool to convert temperatures between Celsius, Fahrenheit and Kelvin."
license = "MIT"
repository = "https://github.com/nathezek/temprature_converter.git"

[dependencies]
